### ISSUE TITLE
Feature: Create Favorite Movies

### ISSUE THREAD

**Issue by leohmoraes** [estudos-2022/crud-laravel8-app#21]
### Tasks

- [ ] Create Test with Use Cases
- [ ] Connect API  Movie Database (https://github.com/php-tmdb/laravel)
- [ ] Create Resources: Model, Controller, Migrations, Seeds : my_movies
- [ ] Create Frontend 

### Use Cases

- [ ] List and seach movies from API Database
- [ ] Add favorite movie 
- [ ] List favorite movie
- [ ] Remove favorite movie
