### ISSUE TITLE
Feature: Add Products Management with Tags

### ISSUE THREAD

**Issue by leohmoraes** [estudos-2022/crud-laravel8-app#22]
### Resume

CRUD of products, tags with List/Search

### Use Cases

- [ ] CRUD Products with pagination
- [ ] CRUD Tags with pagination
- [ ] One Product can be more than 1 tag
- [ ] Report: Tags -> Total Products

### Schema 

````
CREATE TABLE `product` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
);
CREATE TABLE `tag` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
);
CREATE TABLE `product_tag` (
   `product_id` int NOT NULL,
   `tag_id` int NOT NULL,
   PRIMARY KEY (`product_id`,`tag_id`),
   CONSTRAINT `product_id` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`),
   CONSTRAINT `tag_id` FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`)
);
````

### Tasks

- [ ] Create Test Unit
- [ ] Create Products: Resources, Routes, MVC, Migrations and Seeds
- [ ] Create Test Unit
- [ ] Create Tags: Resources, Routes, MVC, Migrations and Seeds
- [ ] Create Test Unit of Relantionship
- [ ] Create Report (Route, Controller, View)
- [ ] Add instructions in Readme
- [ ] Share SQL of Report in Readme
